version: '3.1'

services:
  db:
    image: mysql:8.0.33
    restart: always
    container_name: jwt_database
    environment:
      MYSQL_ROOT_PASSWORD: helloRoot
      MYSQL_DATABASE: login
      MYSQL_USER: spring
      MYSQL_PASSWORD: helloSpring
    volumes:
      - 'mysql_db:/var/lib/mysql'

  jwt_app:
    image: stingnakamura/jwt_app:1.0.0
    container_name: jwt_app
    command: 'java -jar /app/target/jwt_security-1.0.0.jar'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: spring
      MYSQL_PASSWORD: helloSpring
      JWT_SECRET: cm91Z2hwbGFudGJvdHRsZWltcHJvdmVtYXN0ZXJzbm93Y291cnRnb3JhZGlvcHJvYmw=
    ports:
      - '8080:8080'

volumes:
  mysql_db:
