version: '3.1'

services:
  db:
    image: mysql:8.0.33
    restart: always
    container_name: jwt_database
    environment:
      MYSQL_ROOT_PASSWORD: helloRoot
      MYSQL_DATABASE: login
      MYSQL_USER: spring
      MYSQL_PASSWORD: helloSpring
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '3306:3306'